// frontend/src/pages/Login.jsx
import React, { useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import "./Login.css";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const res = await axios.post("http://localhost:5000/auth/login", {
        email,
        password,
      });

      console.log("Login Response:", res.data); // 🔎 Debug

      localStorage.setItem("access_token", res.data.access_token);
      localStorage.setItem("role", res.data.role);

      // Normalize role to lowercase
      const role = res.data.role.toLowerCase();

if (role === "superadmin" || role === "super_admin") {
  navigate("/superadmin-dashboard");
} else if (role === "admin") {
  navigate("/admin-dashboard");
} else if (role === "agent") {
  navigate("/agent-dashboard");
} else if (role === "customer") {
  navigate("/customer-dashboard");
} else {
  navigate("/");
}

    } catch (err) {
      console.error("Login error:", err);
      setError("Invalid email or password");
    }
  };

  return (
    <div className="login-container">
      <form onSubmit={handleSubmit}>
        <h2>Login</h2>
        <input
          type="email"
          placeholder="Enter Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />
        <input
          type="password"
          placeholder="Enter Password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
          autoComplete="current-password"
        />
        <button type="submit">Login</button>
        {error && <p className="error">{error}</p>}
      </form>
    </div>
  );
}

// frontend/src/views/Login.vue
<template>
  <div class="login-container">
    <h2>Login</h2>
    <form @submit.prevent="handleLogin">
      <input v-model="email" type="email" placeholder="Email" required />
      <input v-model="password" type="password" placeholder="Password" required />
      <button type="submit">Login</button>
    </form>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { login } from '@/utils/api' // ⬅️ Import your API helper function

const router = useRouter()
const email = ref('')
const password = ref('')

const handleLogin = async () => {
  try {
    const res = await login(email.value, password.value)
    console.log('Login success:', res.data)

    // Save token in localStorage
    localStorage.setItem('access_token', res.data.access_token)

    // Redirect to dashboard or home
    router.push('/dashboard')
  } catch (err) {
    console.error('Login failed:', err.response?.data || err.message)
  }
}
</script>

<style scoped>
.login-container {
  max-width: 400px;
  margin: auto;
  padding: 20px;
  background: #f8f8f8;
  border-radius: 8px;
}
input {
  width: 100%;
  padding: 10px;
  margin-bottom: 10px;
}
button {
  width: 100%;
  padding: 10px;
  background: #007bff;
  color: #fff;
  border: none;
  cursor: pointer;
}
</style>
